# Generated by Django 3.2.8 on 2021-10-16 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='static/images/default/avatar/default.png', upload_to=profiles.models.user_directory_path)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True, max_length=1024)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('modify_other_profiles', 'Allows the user to modify other profiles (Admin Access)'),),
            },
        ),
    ]
