# Generated by Django 3.2.8 on 2021-10-25 20:37

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/default/avatar/default.png', upload_to=profiles.models.user_directory_path),
        ),
    ]
