# Generated by Django 3.2.8 on 2021-12-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='countryCallingCode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='countryCode',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
