# Generated by Django 3.2.8 on 2021-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='internationalNumber',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
