# Generated by Django 3.2.8 on 2021-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
