# Generated by Django 3.2.8 on 2021-12-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
