# Generated by Django 3.2.8 on 2021-10-27 15:32

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=products.models.image_path),
        ),
    ]
